# Dev config for running tests and building under Mac
# a local Docker Compose cluster needs to run with Postgres, Redis, etc.
[rest]
port = "8080"
timeout = 10

[static]
port = "8081"
timeout = 10

[healthcheck]
port = "8082"
timeout = 10

[postgres]
host = "localhost"
name = "replaceme"
user = "replaceme"
password = "replaceme"
port = "5432"
sslmode = "disable"

[mongo]
host = "localhost"
name = "mongo_db"
user = "root"
password = "root"
port = "27017"
ssl = false

[redis]
host = "localhost"
port = "6379"
password = "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
database = 0

[logging]
level = "debug"
development = true