name: CI-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Install deps
      run: |
        make deps

    - name: Build the docker compose stack
      run: |
        make up

    - name: Build binary
      run: |
        make build

    - name: Test
      run: |
        make test-ci

    - name: Build docs
      run: |
        make swag

    - name: Cleanup job
      if: always()
      run: |
        make clean
